const express = require('express');
const app = express();
const main= require('./routers/main-router.js')
const image= require('./routers/image-router.js')
const {connect, users}= require('./db/db.js')
const {User, newCreate, double}= require('./db/create.js')
require("dotenv").config()
const cors = require('cors');
const PORT= process.env.PORT;

const users1=[
    {
        insta:"ynw._abby._",
        id:46,
        votes:1000,
        gender:"female"
    },
    {
        insta:"wangarii.nw",
        id:47,
        votes:1000,
        gender:"female"
    },
    {
        insta:"lisaaa._wk",
        id:48,
        votes:1000,
        gender:"female"
    },
    {
        insta:"_.sambs_",
        id:49,
        votes:1000,
        gender:"female"
    },
    {
        insta:"_savvy.k",
        id:50,
        votes:1000,
        gender:"female"
    },
    {
        insta:"wamuyuu_",
        id:51,
        votes:1000,
        gender:"female"
    },
    {
        insta:"3_lx.ie",
        id:52,
        votes:1000,
        gender:"female"
    },
    {
        insta:"_kendi.main_",
        id:53,
        votes:1000,
        gender:"female"
    },
    {
        insta:"_.itskhloe_",
        id:54,
        votes:1000,
        gender:"female"
    },
    {
        insta:"sarah.brooke_",
        id:55,
        votes:1000,
        gender:"female"
    },
    {
        insta:"imani.agutu",
        id:56,
        votes:1000,
        gender:"female"
    },
    {
        insta:"make.nadiva",
        id:57,
        votes:1000,
        gender:"female"
    },
    {
        insta:"sorayyaaa._._",
        id:58,
        votes:1000,
        gender:"female"
    },
    {
        insta:"av__realll",
        id:59,
        votes:1000,
        gender:"female"
    },
    {
        insta:"txdi.wa",
        id:60,
        votes:1000,
        gender:"female"
    },
    {
        insta:"_.joan1na",
        id:61,
        votes:1000,
        gender:"female"
    },
    {
        insta:"phy._phy_",
        id:62,
        votes:1000,
        gender:"female"
    },
    {
        insta:"jy.imanii",
        id:63,
        votes:1000,
        gender:"female"
    },
    {
        insta:"m4zlani_",
        id:64,
        votes:1000,
        gender:"female"
    },
    {
        insta:"j3sh1l",
        id:65,
        votes:1000,
        gender:"female"
    },
    {
        insta:"gloria.supremacy_",
        id:66,
        votes:1000,
        gender:"female"
    },
    {
        insta:"wa_njirx",
        id:67,
        votes:1000,
        gender:"female"
    },
    {
        insta:"_.zvhrx._",
        id:68,
        votes:1000,
        gender:"female"
    },
    {
        insta:"soraya_0x",
        id:69,
        votes:1000,
        gender:"female"
    },
    {
        insta:"luv_sxmmie",
        id:70,
        votes:1000,
        gender:"female"
    },
    {
        insta:"joyy.wm",
        id:71,
        votes:1000,
        gender:"female"
    },
    {
        insta:"lindii.xoxo",
        id:72,
        votes:1000,
        gender:"female"
    },
    {
        insta:"pgl.bella",
        id:73,
        votes:1000,
        gender:"female"
    },
    {
        insta:"t_r1za",
        id:74,
        votes:1000,
        gender:"female"
    },
    {
        insta:"pty.imxni",
        id:75,
        votes:1000,
        gender:"female"
    },
    {
        insta:"nanati__t",
        id:76,
        votes:1000,
        gender:"female"
    },
    {
        insta:"mw.kyra",
        id:77,
        votes:1000,
        gender:"female"
    },
    {
        insta:"s1maloi._",
        id:78,
        votes:1000,
        gender:"female"
    },
    {
        insta:"cindx.ylr",
        id:79,
        votes:1000,
        gender:"female"
    },
    {
        insta:"_.tuuugi",
        id:80,
        votes:1000,
        gender:"female"
    },
    {
        insta:"_.avisaaaa._",
        id:81,
        votes:1000,
        gender:"female"
    },
    {
        insta:"imani.nafula",
        id:82,
        votes:1000,
        gender:"female"
    },
    {
        insta:"p3ndo_szn",
        id:83,
        votes:1000,
        gender:"female"
    },
    {
        insta:"yasmin._yf",
        id:84,
        votes:1000,
        gender:"female"
    },
    {
        insta:"zawad.iii_",
        id:85,
        votes:1000,
        gender:"female"
    },
    {
        insta:"nesss_.sssaaa",
        id:86,
        votes:1000,
        gender:"female"
    },
    {
        insta:"nataliaa.szn",
        id:87,
        votes:1000,
        gender:"female"
    },
    {
        insta:"_rb.e.l.l.a._0",
        id:88,
        votes:1000,
        gender:"female"
    },
    {
        insta:"just__catrina",
        id:89,
        votes:1000,
        gender:"female"
    },
    {
        insta:"karecancook",
        id:90,
        votes:1000,
        gender:"female"
    },
    {
        insta:"nyambur.aa._",
        id:91,
        votes:1000,
        gender:"female"
    },
    {
        insta:"bigbabydebby",
        id:92,
        votes:1000,
        gender:"female"
    },
    {
        insta:"__its_wakanyi",
        id:93,
        votes:1000,
        gender:"female"
    },
    {
        insta:"mendyy.szn",
        id:94,
        votes:1000,
        gender:"female"
    },
    {
        insta:"k3ndii.supremacy_",
        id:95,
        votes:1000,
        gender:"female"
    },

]

connect()


app.use(cors())
app.use(express.json())
app.use('/app', main)
app.use('/api', image)


//main page-'/'DONE TESTED MADE
//about-'/app/about' DONE TESTED MADE
//leaderboards-'/app/leaderboards' DONE TESTED
//leaderboards-'/app/leaderboards/:name' DONE TESTED
//deadlock-'/app/deadlock' DONE TESTED
//images-'/api/images' DONE TESTED
//add-'/app/add/:insta DONE TESTED MADE
//connect an move everything to mongoDB DONE TESTED MADE
//adding a vote '/api/vote' DONE TESTED 

app.get('/', async(req,res)=>{
    res.status(200).json(await users())
})


app.listen(PORT,()=>{
    console.log("listening...")
})
//http://localhost:3000/